ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS notification_email_status_updates BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS notification_email_comments BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS notification_email_assignments BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS notification_email_system_messages BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS notification_channel_email BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS notification_channel_in_app BOOLEAN NOT NULL DEFAULT FALSE;
